#[cfg(test)]
mod tests {
    use crate::helpers::LockupContract;
    use crate::msg::InstantiateMsg;
    use cosmwasm_std::testing::MockApi;
    use cosmwasm_std::{Addr, Coin, Decimal, Empty, Uint128};
    use cw_multi_test::{App, AppBuilder, Contract, ContractWrapper, Executor};

    pub fn contract_template() -> Box<dyn Contract<Empty>> {
        let contract = ContractWrapper::new(
            crate::contract::execute,
            crate::contract::instantiate,
            crate::contract::query,
        );
        Box::new(contract)
    }

    const USER: &str = "USER";
    const ADMIN: &str = "ADMIN";
    const NATIVE_DENOM: &str = "uc4e";

    fn mock_app() -> App {
        AppBuilder::new().build(|router, _, storage| {
            router
                .bank
                .init_balance(
                    storage,
                    &MockApi::default().addr_make(USER),
                    vec![Coin {
                        denom: NATIVE_DENOM.to_string(),
                        amount: Uint128::new(1_000_000_000_000u128),
                    }],
                )
                .unwrap();

            // give admin some funds too for deposits
            router
                .bank
                .init_balance(
                    storage,
                    &MockApi::default().addr_make(ADMIN),
                    vec![Coin {
                        denom: NATIVE_DENOM.to_string(),
                        amount: Uint128::new(1_000_000_000_000_000_000_000_000u128),
                    }],
                )
                .unwrap();
        })
    }

    fn proper_instantiate() -> (App, LockupContract) {
        let mut app = mock_app();
        let lockup_contract_id = app.store_code(contract_template());

        let user = app.api().addr_make(USER);
        assert_eq!(
            app.wrap().query_balance(user, NATIVE_DENOM).unwrap().amount,
            Uint128::new(1_000_000_000_000u128)
        );

        let msg = InstantiateMsg {
            admins: None,
            denom: NATIVE_DENOM.to_string(),
            lockup_duration_seconds: 86400, // 1 day for testing
            tier_config: crate::state::TierConfig {
                tier_1_min: Uint128::new(10_000 * 1_000_000),                                       // 10K C4E
                tier_2_min: Uint128::new(50_000 * 1_000_000),                                       // 50K C4E
                tier_3_min: Uint128::new(100_000 * 1_000_000),                                      // 100K C4E
                tier_4_min: Uint128::new(500_000 * 1_000_000),                                      // 500K C4E
                tier_4_limit: Uint128::new(1_000_000 * 1_000_000),                                  // 1M C4E
                tier_1_apr: Decimal::percent(2),                                                    // 2%
                tier_2_apr: Decimal::from_atomics(35u32, 3).unwrap(),       // 3.5%
                tier_3_apr: Decimal::percent(5),                                                    // 5%
                tier_4_apr: Decimal::percent(8),                                                    // 8%
                percentage_increase_per_year: Decimal::percent(1),                                  // 1% increase per year past lockup
                max_percentage_increase: Decimal::percent(10),                                       // 10% max increase
            },
        };
        let lockup_contract_addr = app
            .instantiate_contract(
                lockup_contract_id,
                Addr::unchecked(ADMIN),
                &msg,
                &[],
                "lockup-contract",
                None,
            )
            .unwrap();

        let lockup_contract = LockupContract(lockup_contract_addr);

        (app, lockup_contract)
    }

    mod lockup {
        use super::*;
        use crate::msg::ExecuteMsg;

        #[test]
        fn test_lock() {
            let (mut app, lockup_contract) = proper_instantiate();

            // use proper address generated by MockApi
            let user_addr = app.api().addr_make(USER);

            // check initial balances
            let user_balance = app.wrap().query_balance(&user_addr, NATIVE_DENOM).unwrap();
            println!("User balance: {}", user_balance.amount);

            let lock_amount = Coin::new(10_000_000_000u128, NATIVE_DENOM); // 10 000 C4E
            let msg = ExecuteMsg::Lock {};                                  // uses configured duration

            let result =
                app.execute_contract(user_addr, lockup_contract.addr(), &msg, &[lock_amount]);

            match result {
                Ok(_) => println!("Lock successful"),
                Err(e) => println!("Lock failed: {}", e),
            }
        }
    }
}
